language: scala

scala:
  - 2.11.6

before_install:
 - git clone -b macroparser git@github.com:Duhemm/scala.git scala-macroparser
 - cd scala-macroparser
 - ant

sbt_args: -Dmacroparser.scala.home="scala-macroparser/build/pack"

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update cmp tests/test
